sudo: false
language: c
cache:
  directories:
    - ./cache
jobs:
  include:
  - stage: first
    env:
      - FOO=1
      - CACHE_NAME=shared
    script: mkdir -p ./cache && echo $RANDOM > ./cache/random
  - stage: first
    env:
      - FOO=2
    script: mkdir -p ./cache && echo $RANDOM > ./cache/random
  - stage: second
    env:
      - FOO=1
      - CACHE_NAME=shared
    script: cat ./cache/random
  - stage: second
    env:
      - FOO=2
      - CACHE_NAME=shared
    script: cat ./cache/random
  - stage: second
    env:
      - FOO=2
    script: cat ./cache/random